### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by Anaphory** [clld/clldclient#7]
Trying to use the lexibank code for my languages, I run into a similar problem to #4. Just like @cysouw, I am using python3.5. I have adapted lexibank to work with python3 and clld 2 (changing print statements to functions calls, replacing jsonread() calls with json.read(open()) calls, substituting clld.utils with clldutils, those kinds of things).

Now I have added a singular very minimal data entry referencing a glottolog language in my data, with my dummy entry in the `data.csv` looking as follows.

```
"Value","Feature_ID","Language_ID"
"e","http://someconcept.db/e","http://glottolog.org/resource/languoid/id/tetu1245"
```

Running the `initializedb.py` script to add this to the database, clldclient dies with the following traceback.

```
ERROR
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "p:\my documents\database\clld_core\clld\scripts\util.py", line 234, in initializedb
    create(args)
  File "p:/My Documents/Database/lexibank/lexibank/scripts/initializedb.py", line 40, in main
    import_cldf(os.path.join(datadir, provider, 'cldf'), provider)
  File "p:\my documents\database\lexibank\lexibank\scripts\util.py", line 124, in import_cldf
    import_dataset(os.path.join(dirpath, fname), provider)
  File "p:\my documents\database\lexibank\lexibank\scripts\util.py", line 73, in import_dataset
    languoid = glottolog.languoid(row['Language_ID'])
  File "c:\Users\me\AppData\Local\Continuum\Anaconda3\lib\site-packages\clldclient-1.3.2-py3.5.egg\clldclient\glottolog.py", line 40, in languoid
    return self.resource(code, 'language')
  File "c:\Users\me\AppData\Local\Continuum\Anaconda3\lib\site-packages\clldclient-1.3.2-py3.5.egg\clldclient\database.py", line 226, in resource
    rtype = get_resource_type(res.content, URIRef(res.canonical_url))
  File "c:\Users\me\AppData\Local\Continuum\Anaconda3\lib\site-packages\rdflib-4.2.1-py3.5.egg\rdflib\term.py", line 206, in __new__
    if not _is_valid_uri(value):
  File "c:\Users\me\AppData\Local\Continuum\Anaconda3\lib\site-packages\rdflib-4.2.1-py3.5.egg\rdflib\term.py", line 77, in _is_valid_uri
    if c in uri: return False
TypeError: a bytes-like object is required, not 'str'
```

This behaviour is functionally identical no matter whether the entry in the cache exists or not.
When the cache entry does not exist, `cache.Cache.add()` executes the encoding explicitly, and when it does exist, the database returns the raw `bytes` objects.
Either I did something wrong while testing\*  – or it does not help to define the corresponding `responses` table columns as `String(convert_unicode=True)` either.

I would place the source of this error in `database.Database.get()`, because the types of attributes in `database.Database.resource()` are still `str` [before that call](https://github.com/clld/clldclient/blob/e98b049243c1709fba33d7be714fc86d3ff3656e/clldclient/database.py#L222), but that function reads raw bytes from the database without decoding.

I assume there are two ways to solve this issue:
Either add explicit decoding to `Database.get()`, or be cleverer than myself about database column types and set the column type logic in the `responses` table to some appropriate value of “Unicode in python 2 and String in python 3” and let `sqlalchemy` deal with the coding issues.

*) Which is quite likely, it took me a while to get the grasp of the program flow, and I may have missed saving once before investigating that branch, or I may have had a case of “cache is empty, encoding is done explicitly in `add`, not due to being read from the db” when trying to test it, or I missed something about how columns are defined, or something else. Going to retest.

**Comment by Anaphory** [comment]
Actually, it looks like my testing was indeed off:

Removing the `.encode('utf-8')` calls from `cache.Cache.add` and defining all appropriate `responses` columns to be `String(convert_unicode=True)` seems to work (for my setup, there may be encoding issues for other versions of packages), both for empty cache and for reading entries from cache.

(Patch to follow, I seem to have edited the non-symlinked installed python egg instead of the git working copy…)

**Comment by xrotwang** [comment]
Yeah, supporting py2 and py3 for issues dealing with file paths, HTTP content and headers, etc. is a bit of a pain. I'll look forward to your pull request :)
